---
title: "COVID-19 and Online Learning Tools"
author:
- familyname: Talagala 
  othernames: Priyanga Dilini
  address: Department of Compuational Mathematics, University of Moratuwa, Sri Lanka
  email: priyangad@uom.lk
  correspondingauthor: true
- familyname: Talagala
  othernames: Thiyanga S.
  address: Department of Statistics, Faculty of Applied Sciences, University of Sri Jayewardenepura, Sri Lanka
  email: ttalagala@sjp.ac.lk
abstract: "Distance education has a long history. However, COVID-19 has created a new era of distance education. Due to the increasing demand, various distance learning solutions have been introduced for different distance education purposes. In this study, we investigated the impact of COVID-19 on global attention towards different distance learning-teaching tools. We used Google Trend search queries as a proxy to quantify the  popularity and public interest towards different distance education solutions. Both visual and analytical approaches were used to  analyse global level web search queries during the COVID-19 pandemic. This can provide a fast first step guide to identifying the most popular online learning tools available for different educational purposes.  The results allow the teachers to narrow down the search space and deepen their exploration of prominent distance education solutions to support their online teaching.  The R code and data to reproduce the results of this work are available in the online supplementary materials."
keywords:  "Online learning, Online teaching Distance education solutions, COVID-19 Pandemic,  Google Trend search queries"
wpnumber: 1
jelcodes: C82,I20,I21
blind: false
cover: true
toc: false
bibliography: references.bib
biblio-style: authoryear-comp
output:
  templatehub::workingpaper:
    fig_caption: yes
    fig_height: 10
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=FALSE, messages=FALSE, warning=FALSE)
# Make sure you have the latest version of rmarkdown and bookdown
#devtools::install_github("rstudio/rmarkdown")
#devtools::install_github("rstudio/bookdown")
library(ggplot2)
```


```{r main, child='main.Rmd'}
```

